/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pruebas;
import Clases.Arista;
import Clases.Grafo;
import Clases.Vertice;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Modificaciones.implementartextArea;
/**
 *
 * @author diego123
 */
public class GrafoD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GrafoD.class.getName());
    private Grafo grafo = new Grafo();
    private Vertice verticeMouse = null; //este solamente en caso de que no de click a nada
    private boolean insertarAri = false;
    private Vertice ORI = null; 
    private Vertice DESTI = null;
    /**
     * Creates new form GrafoD
     */
    public GrafoD() {
        PanelDibujoGrafo = new JPanel(){
            @Override
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                dibujar(g);
            }
        };
        initComponents();
        
        Mouse();
    }
    private void dibujar(Graphics g){
        for (Arista ari : grafo.getAri()) {
                ari.pintar(g);
        }
        
        for (int i = 0; i < grafo.verticesT(); i++) {
            Vertice v = grafo.getVertice(i);
            v.pintar(g);
        }
    }
    
    private void Mouse(){
        PanelDibujoGrafo.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e){
                if (!insertarAri){
                    for(int i = 0; i<grafo.verticesT(); i++){
                        Vertice v = grafo.getVertice(i);
                        Rectangle r = new Rectangle(v.getX() - Vertice.d/2, v.getY() - Vertice.d/2, 
                                Vertice.d, Vertice.d);
                        if(r.contains(e.getPoint())){
                            verticeMouse = v; break;
                        }
                    }
                    return;
                }
                if(e.getButton() == MouseEvent.BUTTON3){
                    Vertice v = null;
                    for (int i = 0; i < grafo.verticesT(); i++) {
                        Vertice ve = grafo.getVertice(i);
                        Rectangle r = new Rectangle(ve.getX() - Vertice.d/2, ve.getY() - Vertice.d/2,
                                Vertice.d, Vertice.d);
                        
                        if(r.contains(e.getPoint())){
                            v = ve; break;
                        }
                    }
                    if (v == null) return;
                    
                    if(ORI == null){
                        ORI = v;
                        return;
                    }
                    
                    if(DESTI == null){
                        if(v == ORI) return;
                        DESTI = v;
                    }
                    
                    grafo.AgregarArista(ORI.getNombre(), DESTI.getNombre());
                    
                    implementartextArea mode = new implementartextArea(grafo);
                    Matriz.setText(mode.obMatriz()); 
                    
                    ORI = null; DESTI = null; insertarAri = false;
                    PanelDibujoGrafo.repaint();
                }
            }
            
            @Override
            public void mouseReleased(MouseEvent e){
                verticeMouse = null;
            }
        });
        PanelDibujoGrafo.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e){
                if(verticeMouse != null){
                    verticeMouse.setX(e.getX());
                    verticeMouse.setY(e.getY());
                    PanelDibujoGrafo.repaint();
                }
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDibujoGrafo = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                dibujar(g);
            }
        }
        ;
        jPanel1 = new javax.swing.JPanel();
        InsertarVertice = new javax.swing.JButton();
        EliminarVertice = new javax.swing.JButton();
        InsertarArista = new javax.swing.JButton();
        EliminarArista = new javax.swing.JButton();
        MostrarRecorrido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtextRecorridos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Matriz = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIBUJAR UN GRAFO");

        PanelDibujoGrafo.setBackground(new java.awt.Color(204, 204, 255));
        PanelDibujoGrafo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));

        javax.swing.GroupLayout PanelDibujoGrafoLayout = new javax.swing.GroupLayout(PanelDibujoGrafo);
        PanelDibujoGrafo.setLayout(PanelDibujoGrafoLayout);
        PanelDibujoGrafoLayout.setHorizontalGroup(
            PanelDibujoGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
        );
        PanelDibujoGrafoLayout.setVerticalGroup(
            PanelDibujoGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERACIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 13))); // NOI18N

        InsertarVertice.setText("Insertar Vertice");
        InsertarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarVerticeActionPerformed(evt);
            }
        });

        EliminarVertice.setText("Eliminar Vertice");
        EliminarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVerticeActionPerformed(evt);
            }
        });

        InsertarArista.setText("Insertar Arista");
        InsertarArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarAristaActionPerformed(evt);
            }
        });

        EliminarArista.setText("Eliminar Arista");
        EliminarArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAristaActionPerformed(evt);
            }
        });

        MostrarRecorrido.setText("Mostrar Recorridos");
        MostrarRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarRecorridoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(InsertarArista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InsertarVertice, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EliminarVertice, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(EliminarArista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(MostrarRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarArista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarArista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MostrarRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JtextRecorridos.setColumns(20);
        JtextRecorridos.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        JtextRecorridos.setRows(5);
        JtextRecorridos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECORRIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(JtextRecorridos);

        Matriz.setColumns(20);
        Matriz.setFont(new java.awt.Font("Georgia", 3, 16)); // NOI18N
        Matriz.setRows(5);
        Matriz.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MATRIZ DE ADYACENCIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(Matriz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDibujoGrafo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDibujoGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarVerticeActionPerformed
        String NomVertice = JOptionPane.showInputDialog("Ingrese el nombre del vertice");
        
        if(NomVertice != null && !NomVertice.trim().isEmpty()){
            try{
                if (grafo.buscar(NomVertice) != -1) throw new Exception("el vertice con el nombre " + NomVertice + " ya existe");
                grafo.AgregarVertice(NomVertice.trim());
                
                //dado a que no ingresamos vertices dando click en el panel, se aplica una forma de ingresarlos
                //y acomodarlos aleatoriamente
                Vertice nuevoVertice = grafo.getVertice(grafo.verticesT() - 1);
                int x = 50 + (int)(Math.random() * (PanelDibujoGrafo.getWidth() - 100));
                int y = 50 + (int)(Math.random() * (PanelDibujoGrafo.getHeight() - 100));
                nuevoVertice.setX(x);
                nuevoVertice.setY(y);
                
                PanelDibujoGrafo.repaint();
                JOptionPane.showMessageDialog(null, "Vertice " + NomVertice + " agregado correctamente");
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }else
            return;
    }//GEN-LAST:event_InsertarVerticeActionPerformed

    private void EliminarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVerticeActionPerformed
        String NomVertice = JOptionPane.showInputDialog("Ingrese el nombre del vertice para eliminarlo");
        
        if (NomVertice != null && !NomVertice.trim().isEmpty()){
            try{
                if(grafo.buscar(NomVertice) == -1) throw new Exception("el vertice con el nombre " + NomVertice + " no existe");
                grafo.eliminarVertice(NomVertice.trim());
                
                
                PanelDibujoGrafo.repaint();
                
                implementartextArea mode = new implementartextArea(grafo);
                Matriz.setText(mode.obMatriz()); 
                
                JOptionPane.showMessageDialog(null, "Vertice " + NomVertice + " eliminado correctamente");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else
            return;
    }//GEN-LAST:event_EliminarVerticeActionPerformed

    private void InsertarAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarAristaActionPerformed
        insertarAri = true;
        ORI = null;
        DESTI = null;
    }//GEN-LAST:event_InsertarAristaActionPerformed

    private void EliminarAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAristaActionPerformed
        int O, D;
        String ori = JOptionPane.showInputDialog("¿Cual es el vertice origen?");
        String des = JOptionPane.showInputDialog("¿cual es el vertice destino?");
        
        if (ori != null && des != null && !ori.trim().isEmpty() && !des.trim().isEmpty()){
            try{
                if (grafo.buscar(ori) == -1) throw new Exception("Vertice origen " + ori + " no existe");
                if (grafo.buscar(des) == -1) throw new Exception("Vertice destino " + des + " no existe");
                
                O = grafo.buscar(ori);
                D = grafo.buscar(des);
                
                if(!grafo.aristaE(O, D)) throw new Exception("No existe arista " + ori + "," + des);
                
                grafo.EliminarArista(ori.trim(), des.trim());
                PanelDibujoGrafo.repaint();
                JOptionPane.showMessageDialog(null, "Arista " + ori + "," + des + " eliminada");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + e.getMessage(), "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
            
        }else
            return;
    }//GEN-LAST:event_EliminarAristaActionPerformed

    private void MostrarRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarRecorridoActionPerformed
        String op = (String)JOptionPane.showInputDialog(null, "¿QUE RECORRIDO HARA?", "RECORRIDOS", JOptionPane.INFORMATION_MESSAGE, null,
                new Object[]{"ANCHURA", "PROFUNDIDAD", "AMBOS"}, null);
        if(op == null) return;
        try{
            String vertice = JOptionPane.showInputDialog("Ingrese el vertice de origen");
            if (vertice == null) return;
            
            vertice = vertice.trim();

            implementartextArea mode = new implementartextArea(grafo); //Tengo otra clase que involucra a este objeto
            switch (op) {
                case "ANCHURA":
                    JtextRecorridos.setText(mode.obAnchura(vertice));
                    break;
                case "PROFUNDIDAD":
                    JtextRecorridos.setText(mode.obProfundidad(vertice));
                    break;
                case "AMBOS":
                    JtextRecorridos.setText(mode.obAnchura(vertice) + "\n" + mode.obProfundidad(vertice));
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "ERROR");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_MostrarRecorridoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GrafoD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarArista;
    private javax.swing.JButton EliminarVertice;
    private javax.swing.JButton InsertarArista;
    private javax.swing.JButton InsertarVertice;
    private javax.swing.JTextArea JtextRecorridos;
    private javax.swing.JTextArea Matriz;
    private javax.swing.JButton MostrarRecorrido;
    private javax.swing.JPanel PanelDibujoGrafo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
